In [2]:
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [8]:
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)

In [3]:
# load dataset
dataframe = pandas.read_csv("proj_1.csv", header=None)
dataset = dataframe.values
# split into input (X) and output (Y) variables
X = dataset[:,0:60].astype(float)  # take all rows and first 60 cols
Y = dataset[:,60]

In [4]:
print(X)
# print(Y)

[[0.02   0.0371 0.0428 ... 0.0084 0.009  0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 ...
 [0.0522 0.0437 0.018  ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.026  0.0363 0.0136 ... 0.0036 0.0061 0.0115]]


# The output variable is string values. We must convert them into integer values 0 and 1.We can do this using the LabelEncoder class from scikit-learn. This class will model the encoding required using the entire dataset via the fit() function, then apply the encoding to create a new output variable using the transform() function



In [5]:

# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)

In [6]:

# baseline model
def create_baseline():
    # create model
    model = Sequential()
    model.add(Dense(60, input_dim=60, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [9]:
# evaluate model with standardized dataset
estimator = KerasClassifier(build_fn=create_baseline, epochs=100, batch_size=5, verbose=0)
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X, encoded_Y, cv=kfold)
print("Results: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where








Results: 80.74% (8.11%)


In [ ]:
# Binary Classification with Sonar Dataset: Baseline
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
# load dataset
dataframe = read_csv("proj_1.csv", header=None)
dataset = dataframe.values
# split into input (X) and output (Y) variables
X = dataset[:,0:60].astype(float)
Y = dataset[:,60]
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# baseline model
def create_baseline():
    # create model
    model = Sequential()
    model.add(Dense(60, input_dim=60, activation='relu'))
    model.add(Dense(30, activation='relu'))
    model.add(Dense(30, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model
# evaluate model with standardized dataset
estimator = KerasClassifier(build_fn=create_baseline, epochs=100, batch_size=5, verbose=0)
kfold = StratifiedKFold(n_splits=10, shuffle=True)
results = cross_val_score(estimator, X, encoded_Y, cv=kfold)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

In [10]:

# evaluate baseline model with standardized dataset
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasClassifier(build_fn=create_baseline, epochs=100, batch_size=5, verbose=1)))
pipeline = Pipeline(estimators)
kfold = StratifiedKFold(n_splits=10, shuffle=True)
results = cross_val_score(pipeline, X, encoded_Y, cv=kfold)
print("Standardized: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Epoch 1/100
187/187 [==============================] - 2s 10ms/step - loss: 0.5621 - acc: 0.6738
Epoch 2/100
187/187 [==============================] - 0s 834us/step - loss: 0.4260 - acc: 0.8128
Epoch 3/100
187/187 [==============================] - 0s 706us/step - loss: 0.3618 - acc: 0.8503
Epoch 4/100
187/187 [==============================] - 0s 727us/step - loss: 0.3099 - acc: 0.8877
Epoch 5/100
187/187 [==============================] - 0s 727us/step - loss: 0.2716 - acc: 0.9198
Epoch 6/100
187/187 [==============================] - 0s 727us/step - loss: 0.2373 - acc: 0.9305
Epoch 7/100
187/187 [==============================] - 0s 739us/step - loss: 0.2096 - acc: 0.9465
Epoch 8/100
187/187 [==============================] - 0s 813us/step - loss: 0.1871 - acc: 0.9572
Epoch 9/100
187/187 [==============================] - 0s 727us/step - loss: 0.1658 - acc: 0.9626
Epoch 10/100
187/187 [==============================] - 0s 663us/step - loss: 0.1496 - acc: 0.9786
Epoch 11/100
187/187

187/187 [==============================] - 0s 620us/step - loss: 0.0017 - acc: 1.0000
Epoch 84/100
187/187 [==============================] - 0s 492us/step - loss: 0.0016 - acc: 1.0000
Epoch 85/100
187/187 [==============================] - 0s 534us/step - loss: 0.0016 - acc: 1.0000
Epoch 86/100
187/187 [==============================] - 0s 513us/step - loss: 0.0015 - acc: 1.0000
Epoch 87/100
187/187 [==============================] - 0s 492us/step - loss: 0.0015 - acc: 1.0000
Epoch 88/100
187/187 [==============================] - 0s 556us/step - loss: 0.0014 - acc: 1.0000
Epoch 89/100
187/187 [==============================] - 0s 513us/step - loss: 0.0014 - acc: 1.0000
Epoch 90/100
187/187 [==============================] - 0s 492us/step - loss: 0.0013 - acc: 1.0000
Epoch 91/100
187/187 [==============================] - 0s 727us/step - loss: 0.0013 - acc: 1.0000
Epoch 92/100
187/187 [==============================] - 0s 513us/step - loss: 0.0013 - acc: 1.0000
Epoch 93/100
187/187 [=

187/187 [==============================] - 0s 834us/step - loss: 0.0034 - acc: 1.0000
Epoch 66/100
187/187 [==============================] - 0s 727us/step - loss: 0.0032 - acc: 1.0000
Epoch 67/100
187/187 [==============================] - 0s 642us/step - loss: 0.0031 - acc: 1.0000
Epoch 68/100
187/187 [==============================] - 0s 492us/step - loss: 0.0029 - acc: 1.0000
Epoch 69/100
187/187 [==============================] - 0s 492us/step - loss: 0.0029 - acc: 1.0000
Epoch 70/100
187/187 [==============================] - 0s 513us/step - loss: 0.0027 - acc: 1.0000
Epoch 71/100
187/187 [==============================] - 0s 492us/step - loss: 0.0027 - acc: 1.0000
Epoch 72/100
187/187 [==============================] - 0s 537us/step - loss: 0.0025 - acc: 1.0000
Epoch 73/100
187/187 [==============================] - 0s 513us/step - loss: 0.0025 - acc: 1.0000
Epoch 74/100
187/187 [==============================] - 0s 513us/step - loss: 0.0024 - acc: 1.0000
Epoch 75/100
187/187 [=

187/187 [==============================] - 0s 418us/step - loss: 0.0092 - acc: 1.0000
Epoch 48/100
187/187 [==============================] - 0s 501us/step - loss: 0.0086 - acc: 1.0000
Epoch 49/100
187/187 [==============================] - 0s 547us/step - loss: 0.0082 - acc: 1.0000
Epoch 50/100
187/187 [==============================] - 0s 486us/step - loss: 0.0078 - acc: 1.0000
Epoch 51/100
187/187 [==============================] - 0s 484us/step - loss: 0.0075 - acc: 1.0000
Epoch 52/100
187/187 [==============================] - 0s 399us/step - loss: 0.0071 - acc: 1.0000
Epoch 53/100
187/187 [==============================] - 0s 501us/step - loss: 0.0068 - acc: 1.0000
Epoch 54/100
187/187 [==============================] - 0s 594us/step - loss: 0.0065 - acc: 1.0000
Epoch 55/100
187/187 [==============================] - 0s 538us/step - loss: 0.0061 - acc: 1.0000
Epoch 56/100
187/187 [==============================] - 0s 418us/step - loss: 0.0059 - acc: 1.0000
Epoch 57/100
187/187 [=

187/187 [==============================] - 0s 501us/step - loss: 0.0260 - acc: 1.0000
Epoch 30/100
187/187 [==============================] - 0s 418us/step - loss: 0.0239 - acc: 1.0000
Epoch 31/100
187/187 [==============================] - 0s 501us/step - loss: 0.0223 - acc: 1.0000
Epoch 32/100
187/187 [==============================] - 0s 418us/step - loss: 0.0207 - acc: 1.0000
Epoch 33/100
187/187 [==============================] - 0s 531us/step - loss: 0.0193 - acc: 1.0000
Epoch 34/100
187/187 [==============================] - ETA: 0s - loss: 0.0149 - acc: 1.000 - 0s 379us/step - loss: 0.0179 - acc: 1.0000
Epoch 35/100
187/187 [==============================] - 0s 418us/step - loss: 0.0169 - acc: 1.0000
Epoch 36/100
187/187 [==============================] - 0s 418us/step - loss: 0.0160 - acc: 1.0000
Epoch 37/100
187/187 [==============================] - 0s 501us/step - loss: 0.0149 - acc: 1.0000
Epoch 38/100
187/187 [==============================] - 0s 418us/step - loss: 0.0139

187/187 [==============================] - 0s 501us/step - loss: 0.1347 - acc: 0.9786
Epoch 11/100
187/187 [==============================] - 0s 444us/step - loss: 0.1209 - acc: 0.9840
Epoch 12/100
187/187 [==============================] - 0s 442us/step - loss: 0.1099 - acc: 0.9840
Epoch 13/100
187/187 [==============================] - 0s 418us/step - loss: 0.0995 - acc: 0.9893
Epoch 14/100
187/187 [==============================] - 0s 501us/step - loss: 0.0916 - acc: 0.9947
Epoch 15/100
187/187 [==============================] - 0s 418us/step - loss: 0.0806 - acc: 0.9947
Epoch 16/100
187/187 [==============================] - 0s 418us/step - loss: 0.0722 - acc: 1.0000
Epoch 17/100
187/187 [==============================] - 0s 501us/step - loss: 0.0657 - acc: 1.0000
Epoch 18/100
187/187 [==============================] - 0s 418us/step - loss: 0.0599 - acc: 1.0000
Epoch 19/100
187/187 [==============================] - 0s 418us/step - loss: 0.0535 - acc: 1.0000
Epoch 20/100
187/187 [=

187/187 [==============================] - 0s 418us/step - loss: 0.0013 - acc: 1.0000
Epoch 93/100
187/187 [==============================] - 0s 501us/step - loss: 0.0012 - acc: 1.0000
Epoch 94/100
187/187 [==============================] - 0s 442us/step - loss: 0.0012 - acc: 1.0000
Epoch 95/100
187/187 [==============================] - 0s 410us/step - loss: 0.0011 - acc: 1.0000
Epoch 96/100
187/187 [==============================] - 0s 418us/step - loss: 0.0011 - acc: 1.0000
Epoch 97/100
187/187 [==============================] - 0s 418us/step - loss: 0.0011 - acc: 1.0000
Epoch 98/100
187/187 [==============================] - 0s 501us/step - loss: 0.0011 - acc: 1.0000
Epoch 99/100
187/187 [==============================] - 0s 418us/step - loss: 0.0010 - acc: 1.0000
Epoch 100/100
21/21 [==============================] - 0s 19ms/step
Epoch 1/100
187/187 [==============================] - 2s 9ms/step - loss: 0.6854 - acc: 0.6043
Epoch 2/100
187/187 [==============================] - 0s

187/187 [==============================] - 0s 501us/step - loss: 0.0025 - acc: 1.0000
Epoch 75/100
187/187 [==============================] - 0s 418us/step - loss: 0.0024 - acc: 1.0000
Epoch 76/100
187/187 [==============================] - 0s 418us/step - loss: 0.0023 - acc: 1.0000
Epoch 77/100
187/187 [==============================] - 0s 418us/step - loss: 0.0022 - acc: 1.0000
Epoch 78/100
187/187 [==============================] - 0s 501us/step - loss: 0.0022 - acc: 1.0000
Epoch 79/100
187/187 [==============================] - 0s 418us/step - loss: 0.0021 - acc: 1.0000
Epoch 80/100
187/187 [==============================] - 0s 501us/step - loss: 0.0020 - acc: 1.0000
Epoch 81/100
187/187 [==============================] - 0s 489us/step - loss: 0.0019 - acc: 1.0000
Epoch 82/100
187/187 [==============================] - 0s 449us/step - loss: 0.0019 - acc: 1.0000
Epoch 83/100
187/187 [==============================] - 0s 611us/step - loss: 0.0018 - acc: 1.0000
Epoch 84/100
187/187 [=

187/187 [==============================] - 0s 418us/step - loss: 0.0049 - acc: 1.0000
Epoch 57/100
187/187 [==============================] - 0s 501us/step - loss: 0.0047 - acc: 1.0000
Epoch 58/100
187/187 [==============================] - 0s 418us/step - loss: 0.0045 - acc: 1.0000
Epoch 59/100
187/187 [==============================] - 0s 501us/step - loss: 0.0043 - acc: 1.0000
Epoch 60/100
187/187 [==============================] - 0s 418us/step - loss: 0.0041 - acc: 1.0000
Epoch 61/100
187/187 [==============================] - 0s 418us/step - loss: 0.0039 - acc: 1.0000
Epoch 62/100
187/187 [==============================] - 0s 418us/step - loss: 0.0037 - acc: 1.0000
Epoch 63/100
187/187 [==============================] - 0s 418us/step - loss: 0.0036 - acc: 1.0000
Epoch 64/100
187/187 [==============================] - 0s 418us/step - loss: 0.0034 - acc: 1.0000
Epoch 65/100
187/187 [==============================] - 0s 529us/step - loss: 0.0033 - acc: 1.0000
Epoch 66/100
187/187 [=

187/187 [==============================] - 0s 855us/step - loss: 0.0136 - acc: 1.0000
Epoch 39/100
187/187 [==============================] - 0s 684us/step - loss: 0.0129 - acc: 1.0000
Epoch 40/100
187/187 [==============================] - 0s 663us/step - loss: 0.0120 - acc: 1.0000
Epoch 41/100
187/187 [==============================] - 0s 770us/step - loss: 0.0113 - acc: 1.0000
Epoch 42/100
187/187 [==============================] - 0s 770us/step - loss: 0.0107 - acc: 1.0000
Epoch 43/100
187/187 [==============================] - 0s 877us/step - loss: 0.0101 - acc: 1.0000
Epoch 44/100
187/187 [==============================] - 0s 663us/step - loss: 0.0095 - acc: 1.0000
Epoch 45/100
187/187 [==============================] - 0s 577us/step - loss: 0.0091 - acc: 1.0000
Epoch 46/100
187/187 [==============================] - 0s 642us/step - loss: 0.0086 - acc: 1.0000
Epoch 47/100
187/187 [==============================] - 0s 577us/step - loss: 0.0081 - acc: 1.0000
Epoch 48/100
187/187 [=

188/188 [==============================] - 0s 702us/step - loss: 0.0589 - acc: 1.0000
Epoch 21/100
188/188 [==============================] - 0s 638us/step - loss: 0.0538 - acc: 1.0000
Epoch 22/100
188/188 [==============================] - 0s 532us/step - loss: 0.0489 - acc: 1.0000
Epoch 23/100
188/188 [==============================] - 0s 532us/step - loss: 0.0446 - acc: 1.0000
Epoch 24/100
188/188 [==============================] - 0s 553us/step - loss: 0.0409 - acc: 1.0000
Epoch 25/100
188/188 [==============================] - 0s 533us/step - loss: 0.0370 - acc: 1.0000
Epoch 26/100
188/188 [==============================] - 0s 553us/step - loss: 0.0343 - acc: 1.0000
Epoch 27/100
188/188 [==============================] - 0s 574us/step - loss: 0.0318 - acc: 1.0000
Epoch 28/100
188/188 [==============================] - 0s 681us/step - loss: 0.0291 - acc: 1.0000
Epoch 29/100
188/188 [==============================] - 0s 574us/step - loss: 0.0266 - acc: 1.0000
Epoch 30/100
188/188 [=

188/188 [==============================] - 0s 723us/step - loss: 0.4642 - acc: 0.7713
Epoch 3/100
188/188 [==============================] - 0s 638us/step - loss: 0.3916 - acc: 0.8138
Epoch 4/100
188/188 [==============================] - 0s 617us/step - loss: 0.3387 - acc: 0.8564
Epoch 5/100
188/188 [==============================] - 0s 574us/step - loss: 0.2962 - acc: 0.8830
Epoch 6/100
188/188 [==============================] - 0s 596us/step - loss: 0.2600 - acc: 0.9202
Epoch 7/100
188/188 [==============================] - 0s 596us/step - loss: 0.2291 - acc: 0.9309
Epoch 8/100
188/188 [==============================] - 0s 617us/step - loss: 0.2025 - acc: 0.9468
Epoch 9/100
188/188 [==============================] - 0s 702us/step - loss: 0.1821 - acc: 0.9521
Epoch 10/100
188/188 [==============================] - 0s 574us/step - loss: 0.1641 - acc: 0.9681
Epoch 11/100
188/188 [==============================] - 0s 681us/step - loss: 0.1414 - acc: 0.9840
Epoch 12/100
188/188 [========

188/188 [==============================] - 0s 638us/step - loss: 0.0017 - acc: 1.0000
Epoch 85/100
188/188 [==============================] - 0s 596us/step - loss: 0.0016 - acc: 1.0000
Epoch 86/100
188/188 [==============================] - 0s 553us/step - loss: 0.0016 - acc: 1.0000
Epoch 87/100
188/188 [==============================] - 0s 510us/step - loss: 0.0016 - acc: 1.0000
Epoch 88/100
188/188 [==============================] - 0s 532us/step - loss: 0.0015 - acc: 1.0000
Epoch 89/100
188/188 [==============================] - 0s 532us/step - loss: 0.0014 - acc: 1.0000
Epoch 90/100
188/188 [==============================] - 0s 574us/step - loss: 0.0014 - acc: 1.0000
Epoch 91/100
188/188 [==============================] - 0s 619us/step - loss: 0.0014 - acc: 1.0000
Epoch 92/100
188/188 [==============================] - 0s 518us/step - loss: 0.0013 - acc: 1.0000
Epoch 93/100
188/188 [==============================] - 0s 510us/step - loss: 0.0013 - acc: 1.0000
Epoch 94/100
188/188 [=

In [11]:

# smaller model
def create_smaller():
	# create model
	model = Sequential()
	model.add(Dense(30, input_dim=60, activation='relu'))
	model.add(Dense(1, activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasClassifier(build_fn=create_smaller, epochs=100, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = StratifiedKFold(n_splits=10, shuffle=True)
results = cross_val_score(pipeline, X, encoded_Y, cv=kfold)
print("Smaller: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Smaller: 83.67% (6.57%)


In [12]:
# Binary Classification with Sonar Dataset: Standardized Larger
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
# load dataset
dataframe = read_csv("sonar.csv", header=None)
dataset = dataframe.values
# split into input (X) and output (Y) variables
X = dataset[:,0:60].astype(float)
Y = dataset[:,60]
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# larger model
def create_larger():
	# create model
	model = Sequential()
	model.add(Dense(60, input_dim=60, activation='relu'))
	model.add(Dense(30, activation='relu'))
	model.add(Dense(1, activation='sigmoid'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
estimators = []
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasClassifier(build_fn=create_larger, epochs=100, batch_size=5, verbose=0)))
pipeline = Pipeline(estimators)
kfold = StratifiedKFold(n_splits=10, shuffle=True)
results = cross_val_score(pipeline, X, encoded_Y, cv=kfold)
print("Larger: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Larger: 88.90% (6.83%)
